# Generated by Django 3.2.19 on 2023-05-29 13:37

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('social_protection', '0003_beneficiary_historicalbeneficiary'),
    ]

    operations = [
    ]
