# Generated by Django 3.2.20 on 2023-08-01 14:45

from django.db import migrations

from core.utils import insert_role_right_for_system


class Migration(migrations.Migration):
    dependencies = [
        ('social_protection', '0008_benefitplandatauploadrecords_historicalbenefitplandatauploadrecords'),
    ]

    operations = [
        
    ]
